package Interface_Practice;

public class Bank implements Upi,Netbanking,Wallet{
	public void otp()
	{
		System.out.println("OTP generated by Bank");
	}
	@Override
	public void amazon() {
		System.out.println("Amazon ----UPI");
	}

	@Override
	public void axis() {
	System.out.println("Axis -----UPI");
	}

	@Override
	public void icici() {
		System.out.println("ICICI------UPI");
	}

	@Override
	public void ib() {
		System.out.println("IB--------NETBANKING");
	}

	@Override
	public void nb() {
		System.out.println("NB-----NETBANKING");
	}

	@Override
	public void onlinetransfer() {
	System.out.println("onlinetransfer-----NETBANKING");
	}
	
	@Override
	public void paytm() {
		System.out.println("paytm----Wallet");		
	}
	@Override
	public void phonepe() {
		System.out.println("paytm------phonepe");
	}
	
	@Override
	public void common() {
		System.out.println("Common method for all the interfaces");
		
	}
	public static void main(String[] args) {
		
		Bank b1 = new Bank();
		b1.amazon();
		b1.phonepe();
		b1.common();
		
		// 1 class to class - extends
		// 2 class to interface - implements
		// 3 interface to interface - extends
		
		
		//Wallet w = new Wallet(); // wallet is the interface so we cannot create the object for the interface
		// top casting ---> child class obj can be referred by using the parent class obj ref varibable --- this is called topcasting
		
		Upi u =new Bank();
		u.amazon();
		u.axis();
		u.common();
		u.icici();
		for(;;)
		{
			
		}
		

	}
	
	
	

}
